#!/bin/bash

cd src
tests=`ls -d ./*/`
echo $tests

for test in $tests
do
   test=${test%/}
   test=${test#./}
   echo '--------------------------'
   echo "doing test:" $test
   echo '--------------------------'
   cd $test
   echo building $test...
   idris2 --codegen refc -o $test $test.idr
   echo executing build/exec/$test
   # time it, eat stdout
   [[ -f $test.in ]] && time build/exec/$test < $test.in > /dev/null || time build/exec/$test > /dev/null
   # # require root to clear cache
   # sync && echo 3 > /proc/sys/vm/drop_caches
   cd ..
done

